#!/bin/bash
# Continuous Integration build script.

set -e # Exit on any error
set -x # Echo each command

# Don't run the spring application preloader on ci
export DISABLE_SPRING=1

echo '========== Install Ruby ================================================='
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
rbenv install -s
rbenv version

echo '========== Install Gems ================================================='
bundle install --no-color

echo '========== Prepare Database ============================================='

cat > config/database.yml <<EOF
development:
  adapter: mysql2
  database: etdflow_development

test: &test
  adapter: mysql2
  database: etdflow_test

cucumber:
  <<: *test
EOF

bundle exec rake db:create:all
bundle exec rake db:migrate
bundle exec rake db:test:prepare
bundle exec rake jetty:stop jetty:clean jetty:config jetty:start
sleep 30 # We need to wait a good long time for jetty to fully fire up

echo '========== Unit Tests ==================================================='
bundle exec rspec --no-color spec/unit

echo '========== Component Tests =============================================='
bundle exec rspec --no-color spec/component

echo '========== Integration Tests ============================================'
bundle exec rspec --no-color spec/integration

echo '========== Acceptance Tests ============================================='
bundle exec cucumber --no-color

echo '========== Deploy To Staging ============================================'
current_revision=`git show | awk '/^commit / { print $2 }'`
bundle exec cap qa deploy -s branch=$current_revision

echo '========== System Tests ================================================='
bundle exec rspec --no-color spec.system
