require 'spec_helper'
require 'support/rails'
require 'support/poltergeist'
require 'support/database_cleaner'
require 'support/factories'
require 'support/committee_factory'
require 'support/capybara'
require 'support/basic_auth'
