common: &common
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: etdflow_development

test: &test
  <<: *common
  database: etdflow_test

cucumber:
  <<: *test
